apiVersion: v1
kind: Pod
metadata:
  name: bad-student
spec:
  containers:
  - name: crasher
    image: busybox
    command: ["/bin/sh", "-c", "echo 'CRITICAL: Application failed to allocate memory. Heap out of bounds.'; sleep 10; exit 1"]